### PR TITLE
Fix an issue where UI text is cut into too many segments

### LINKED ISSUE #279: Tool tip text renders with too many line breaks
Tool tip text renders with too many line breaks. This does not happen in original.

sshot001

Tested with both **generals.csf** and **generals.str**.

Tried disabling following hooks:
```
    // Replace Utf8String
    //Hook_Method(0x00402430, &Utf8String::Hook_Ctor2);
    //Hook_Method(0x00401D40, &Utf8String::Hook_Ctor1);
    //Hook_Method(0x0040FB40, static_cast<void (Utf8String::*)(char const *)>(&Utf8String::Concat));
    //Hook_Method(0x004159E0, &Utf8String::Ends_With);
    //Hook_Method(0x00415A40, &Utf8String::Ends_With_No_Case);
    //Hook_Method(0x00415290, &Utf8String::Ensure_Unique_Buffer_Of_Size);
    //Hook_Method(0x00415750, static_cast<void (Utf8String::*)(Utf8String, ...)>(&Utf8String::Format));
    //Hook_Method(0x00415860, static_cast<void (Utf8String::*)(char const *, ...)>(&Utf8String::Format));

    //Hook_Method(0x00415280, &Utf8String::Free_Bytes);
    //Hook_Method(0x00415430, &Utf8String::Get_Buffer_For_Read);
    //Hook_Method(0x00415AA0, &Utf8String::Is_None);
    //Hook_Method(0x0040FB20, &Utf8String::Get_Length);
    //Hook_Method(0x00415AD0, &Utf8String::Next_Token);
    //Hook_Method(0x004F3CD0, &Utf8String::Release_Buffer);
    //Hook_Method(0x00415710, &Utf8String::Remove_Last_Char);
    //Hook_Method(0x0040D640, static_cast<void (Utf8String::*)(char const *)>(&Utf8String::Set));
    //Hook_Method(0x00415920, &Utf8String::Starts_With);
    //Hook_Method(0x00415980, &Utf8String::Starts_With_No_Case);
    //Hook_Method(0x00404210, &Utf8String::Str);
    //Hook_Method(0x00415630, &Utf8String::To_Lower);
    //Hook_Method(0x00415450, &Utf8String::Translate);
    //Hook_Method(0x00415530, &Utf8String::Trim);

    // Replace GameTextManager
    //Hook_Function(0x00418320, &GameTextManager::Create_Game_Text_Interface);
    //Hook_Function(0x0041A020, &GameTextManager::Compare_LUT);
    
    //Hook_Method(0x0051EB90, &Parameter::Get_UI_Text);
    
    // wininstancedata.h
    //Hook_Method(0x006DF300, &WinInstanceData::Hook_Ctor);
    //Hook_Method(0x006DF4C0, &WinInstanceData::Init);
    //Hook_Method(0x006DF680, &WinInstanceData::Set_Text);
    //Hook_Method(0x004F8F30, &WinInstanceData::Get_Text);
    //Hook_Method(0x006DF600, &WinInstanceData::Set_Tooltip_Text);
    //Hook_Method(0x004F93E0, &WinInstanceData::Get_Tooltip_Text);
    //Hook_Method(0x006DF700, &WinInstanceData::Set_VideoBuffer);
```

Any idea where to start looking?

### PR DESCRIPTION
**Pull request by xezon**
Fixes #279

### CODE REVIEW

File: src/w3d/renderer/render2dsentence.cpp [hunk 1]
```diff
@@ -996,7 +996,7 @@ Vector2 Render2DSentenceClass::Build_Sentence_Not_Centered(const unichar_t *text
                         const unichar_t *tmp_text = text;
 
                         while (*tmp_text != U_CHAR('\0')) {
-                            if (*tmp_text < U_CHAR(' ')) {
+                            if (*tmp_text <= U_CHAR(' ')) {
```
Comment (xezon) [inline src/w3d/renderer/render2dsentence.cpp:999]: This is the fix.

**Review by OmniBlade — APPROVED** [review]
