### PR TITLE
Fixes audio volume regression.

### LINKED ISSUE #629: Audio is missing in Game Room
Audio is missing in Game Room. Clicking buttons triggers no sounds. Thyme issue.

shot_20220226_192250_1

### LINKED ISSUE #671: Researching faction upgrades does not produce correct sounds
Researching faction upgrades does not produce correct sounds.

Repro:
- Spawn as China General
- Build Power, Supply, Warfactory
- Build Chainguns upgrade

Result:
Voice says "Upgrade Complete" instead of "Chaingun Upgrade Is Complete".

Commenting following line prevents issue:
```c++
Hook_Any(0x007424B0, Win32GameEngine::Create_Audio_Manager);
```

### PR DESCRIPTION
**Pull request by tomsons26**
fixes #629 fixes #671

### CODE REVIEW

File: src/game/common/audio/audiomanager.cpp [hunk 1]
```diff
@@ -709,17 +709,21 @@ void AudioManager::Set_Audio_Event_Volume_Override(Utf8String event, float vol_o
         Adjust_Volume_Of_Playing_Audio(event, vol_override);
     }
 
-    if (m_eventVolumeList.empty() && vol_override != -1.0f) {
-        m_eventVolumeList.push_back(std::pair<Utf8String, float>(event, vol_override));
-    } else {
-        for (auto it = m_eventVolumeList.begin(); it != m_eventVolumeList.end(); ++it) {
-            if (event == it->first && vol_override != -1.0f) {
-                it->second = vol_override;
+    for (auto it = m_eventVolumeList.begin(); it != m_eventVolumeList.end(); ++it) {
```
Comment (duncanspumpkin) [inline src/game/common/audio/audiomanager.cpp:712]: could make this:
```cpp
auto res = std::find_if(m_eventVolumeList.begin(), m_eventVolumeList.end(), [&event](std::pair<Utf8String, float> item){
   return event == item->first;
}
if (res != m_eventVolumeList.end()){
    if (vol_override == -1.0f){
        m_eventVolumeList.erase(res);
    }
    else {
        res->second = vol_override;
    }
}
else
{
    if(vol_override != -1.0f){
        m_eventVolumeList.push_front(std::pair<Utf8String, float>(event, vol_override));
    }
}
```
Not sure if it reads better or not makes it perhaps a bit clearer as to what all the if's represent.

**Review by duncanspumpkin — APPROVED** [review]
Aligns with my reading of wb.

**Comment by xezon** [comment]
Fixes confirmed. Also fixes the broken Radio messages in Single Player missions.

**Review by xezon — APPROVED** [review]
