### PR TITLE
Fix minor errors in Render2DSentenceClass::Build_Sentence_Centered

### LINKED ISSUE #280: Tool tip text renders with corrupt characters
#279 is possibly related to this issue too but not sure, could be a different branch of the code.
This doesn't happen after unhooking FontCharsClass and Render2DSentenceClass
game dat_W4AcHA6Wyg
Game resolution was 1024x768

### PR DESCRIPTION
**Pull request by xezon**
Fixes #280

### CODE REVIEW

File: src/w3d/renderer/render2dsentence.cpp [hunk 1]
```diff
@@ -845,7 +853,7 @@ void Render2DSentenceClass::Build_Sentence_Centered(const unichar_t *text, int *
 
             if (m_processAmpersand && cur_ch == U_CHAR('&')) {
                 unichar_t next_ch = *text;
-                if (next_ch != U_CHAR('\0') && next_ch > U_CHAR(' ')) {
+                if (next_ch != U_CHAR('\0') && next_ch > U_CHAR(' ') && next_ch != U_CHAR('\n')) {
```
Comment (xezon) [inline src/w3d/renderer/render2dsentence.cpp]: Looks like `next_ch != U_CHAR('\n')` can be omitted because of `next_ch > U_CHAR(' ')`. It's odd this was compiled in though. Hmm.

File: src/w3d/renderer/render2dsentence.cpp [hunk 2]
```diff
@@ -771,6 +771,10 @@ void Render2DSentenceClass::Build_Sentence_Centered(const unichar_t *text, int *
                     break;
                 }
 
+                if (test_ch == U_CHAR('\n')) {
```
Comment (xezon) [inline src/w3d/renderer/render2dsentence.cpp]: This looks like it can be omitted because of the test above. It's odd it was compiled in though.

File: src/w3d/renderer/render2dsentence.cpp [hunk 3]
```diff
@@ -831,7 +836,10 @@ void Render2DSentenceClass::Build_Sentence_Centered(const unichar_t *text, int *
             sentence_width += word_width;
         }
 
-        m_cursor.X = std::max((position.X - sentence_width) * 0.5f, 0.0f);
+        m_cursor.X = (float)(int)((position.X - sentence_width) * 0.5f);
+        if (m_cursor.X < 0.0f) {
+            m_cursor.X = 0.0f;
+        }
```
Comment (xezon) [inline src/w3d/renderer/render2dsentence.cpp]: This change fixes the screwed character positions.

File: src/w3d/renderer/render2dsentence.cpp [hunk 4]
```diff
@@ -781,7 +785,8 @@ void Render2DSentenceClass::Build_Sentence_Centered(const unichar_t *text, int *
                     ampersand_handled = true;
                 }
 
-                unichar_t cur_ch = *cur_text++;
+                unichar_t cur_ch = *cur_text;
+                ++cur_text;
```
Comment (duncanspumpkin) [inline src/w3d/renderer/render2dsentence.cpp:785]: This is identical. Why change?

File: src/w3d/renderer/render2dsentence.cpp (hunk 3 above)
Comment (duncanspumpkin) [reply src/w3d/renderer/render2dsentence.cpp]: You could still use max but make it cast to int to force the truncation

File: src/w3d/renderer/render2dsentence.cpp [hunk 5]
```diff
@@ -862,7 +870,7 @@ void Render2DSentenceClass::Build_Sentence_Centered(const unichar_t *text, int *
 
                 if (cur_ch == U_CHAR(' ')) {
                     m_cursor.X += char_spacing;
-                } else if (cur_ch == U_CHAR('\n') || cur_ch == U_CHAR('\0')) {
+                } else if (cur_ch == U_CHAR('\0') || cur_ch == U_CHAR('\n')) {
```
Comment (duncanspumpkin) [inline src/w3d/renderer/render2dsentence.cpp:866]: Why has this been swapped

File: src/w3d/renderer/render2dsentence.cpp [hunk 6]
```diff
@@ -1005,7 +1012,8 @@ Vector2 Render2DSentenceClass::Build_Sentence_Not_Centered(const unichar_t *text
                                 ++tmp_text;
                             }
 
-                            spacing += m_font->Get_Char_Spacing(*tmp_text++);
+                            spacing += m_font->Get_Char_Spacing(*tmp_text);
+                            ++tmp_text;
```
Comment (duncanspumpkin) [inline src/w3d/renderer/render2dsentence.cpp:1011]: Why this change its identical

File: src/w3d/renderer/render2dsentence.cpp [hunk 7]
```diff
@@ -916,10 +924,7 @@ void Render2DSentenceClass::Build_Sentence_Centered(const unichar_t *text, int *
 
     if (x != nullptr) {
         *x = final_x_pos;
-
-        if (y != nullptr) {
-            *y = 0;
-        }
+        *y = 0;
```
Comment (duncanspumpkin) [inline src/w3d/renderer/render2dsentence.cpp:922]: Revert, should keep the safety check

File: src/w3d/renderer/render2dsentence.cpp (hunk 4 above)
Comment (xezon) [reply src/w3d/renderer/render2dsentence.cpp:785]: It's easier on the eye in this case and compares with the decompile better.

File: src/w3d/renderer/render2dsentence.cpp (hunk 5 above)
Comment (xezon) [reply src/w3d/renderer/render2dsentence.cpp:866]: In the decompile it is in this order and therefore easier to compare against.

File: src/w3d/renderer/render2dsentence.cpp (hunk 6 above)
Comment (xezon) [reply src/w3d/renderer/render2dsentence.cpp:1011]: It's easier on the eye in this case and compares with the decompile better.

File: src/w3d/renderer/render2dsentence.cpp (hunk 7 above)
Comment (xezon) [reply src/w3d/renderer/render2dsentence.cpp:922]: No. It should be different.

File: src/w3d/renderer/render2dsentence.cpp (hunk 4 above)
Comment (duncanspumpkin) [reply src/w3d/renderer/render2dsentence.cpp:785]: It will compile to exactly the same and is the normal convention for this sort of function

File: src/w3d/renderer/render2dsentence.cpp (hunk 3 above)
Comment (xezon) [reply src/w3d/renderer/render2dsentence.cpp]: Yeah, but this compares better with the decompile, so can leave as is. Important is that it works correctly.

File: src/w3d/renderer/render2dsentence.cpp (hunk 7 above)
Comment (duncanspumpkin) [reply src/w3d/renderer/render2dsentence.cpp:922]: Why? Do you have some reason why `y` can never be nullptr?

File: src/w3d/renderer/render2dsentence.cpp (hunk 3 above)
Comment (duncanspumpkin) [reply src/w3d/renderer/render2dsentence.cpp]: It is much harder to read and reason with when you add unnecessary casts at least drop the float cast there is no need to do that twice.

File: src/w3d/renderer/render2dsentence.cpp (hunk 1 above)
Comment (xezon) [reply src/w3d/renderer/render2dsentence.cpp]: Fixed.

File: src/w3d/renderer/render2dsentence.cpp (hunk 2 above)
Comment (xezon) [reply src/w3d/renderer/render2dsentence.cpp]: Fixed.

File: src/w3d/renderer/render2dsentence.cpp (hunk 7 above)
Comment (xezon) [reply src/w3d/renderer/render2dsentence.cpp:922]: I added proper checks.

File: src/w3d/renderer/render2dsentence.cpp (hunk 3 above)
Comment (xezon) [reply src/w3d/renderer/render2dsentence.cpp]: Ok. Changed and tested.
