### PR TITLE
Fixes visual regression in road lighting.

### LINKED ISSUE #398: Visual regression in Road code
game dat_El5rQjz6PJ
Map is Mountain Guns

### PR DESCRIPTION
**Pull request by tomsons26**
Fixes #398

### CODE REVIEW

**Review by jonwil — APPROVED** [review]
Looks good to me.

File: src/platform/w3dengine/client/w3droadbuffer.cpp [hunk 1]
```diff
@@ -200,7 +200,7 @@ void RoadSegment::Update_Seg_Lighting()
 
     for (int i = 0; i < m_numVertex; i++) {
         m_vb[i].diffuse = g_theTerrainRenderObject->Get_Static_Diffuse(
-                              size + (int)(m_vb[i].x / 10.0f + 0.5), size + (int)(m_vb[i].x / 10.0f + 0.5))
+                              size + (int)(m_vb[i].x / 10.0f + 0.5), size + (int)(m_vb[i].y / 10.0f + 0.5))
```
Comment (xezon) [inline src/platform/w3dengine/client/w3droadbuffer.cpp:203]: `10.0f + 0.5f`
or `10.5f`

0.5 is double.
